### ISSUE TITLE
Slow performance for large number of branches

### ISSUE THREAD

**Issue by ccallebs** [ruby-git/ruby-git#291] opened 2016-05-26 03:08 UTC
I know having a lot of branches is generally inadvisable. However, sometimes it's unavoidable. With ~400 total branches, fetching a list of them takes 20 seconds on my machine. I ran a profiler to determine where the bottleneck was and this is what I uncovered:

```
%self      total      self      wait     child     calls  name
 87.16     17.662    17.662     0.000     0.000        2   Readline#readline
  1.26      0.420     0.254     0.000     0.166      180   Hash#each
  1.21      0.245     0.245     0.000     0.000        2   IO#write
  0.82      0.166     0.166     0.000     0.000    62218   Regexp#match
  0.63      0.128     0.128     0.000     0.000    61921   String#split
  0.25      0.051     0.051     0.000     0.000    62104   Array#join
```

It looks like the bulk of the time comes from reading the remote config options in the `Git::Remote` initializer (specifically line 8), which in turn calls `Git::Lib#config_remote`. See below:

```
def config_remote(name)
  hsh = {}
  config_list.each do |key, value|
    if /remote.#{name}/.match(key)
      hsh[key.gsub("remote.#{name}.", '')] = value
    end
  end
  hsh
end
```

Since a new `Git::Remote` object gets initialized for each remote repository, it makes sense that this would be the cause for the slowdown.

---

I'm more than willing to tackle this myself, but was hoping for some direction. My initial thought was to only call `config_remote` once, but realized that people can have multiple remote sources.

**Comment by ccallebs** [comment] 2018-04-02 18:40
@perlun I see that you're maintaining -- should I close this issue? I know it's ~2 years old but I'm still using my branch in a project.

**Comment by perlun** [comment] 2018-04-03 05:38
@ccallebs I enabled the stale bot to try and get some help with cleaning up old issues. Thanks for the effort, I wrote a comment in #292 - let's try to get that one merged, this adds value.

**Comment by jcouball** [comment] 2023-02-28 15:40
Closing this issue. A lot has changed since this issue was reported. If this is still a problem, a new report with new statistics and a reproduction recipe would be appreciated.

**Closed by jcouball** 2023-02-28 15:40 UTC
Labels: pinned
