### ISSUE TITLE
git describe option keys mixed between symbols and strings

### ISSUE THREAD

**Issue by jpslav** [ruby-git/ruby-git#277] opened 2016-02-27 02:18 UTC
In `Git::Lib#describe`, several of the `options` are [referred to with string keys and symbol keys within the same line](https://github.com/schacon/ruby-git/blob/bddcc9f09097ad3d8505a0502b8d84f81ad25a3c/lib/git/lib.rb#L115-L120), e.g.:

``` ruby
arr_opts << "--match=#{opts['match']}" if opts[:match]
```

Which means you can't call describe with a simple hash, because if you set a `:match` key, there won't be anything in a `'match'` key.  

I imagine you want it to just be symbol keys since that's what is mostly used above these lines?

Workarounds:
1. Pass both symbol and string keys (duplicated) to the command, e.g.  
   `git.describe(nil, {:match => "*foo*", 'match' => "*foo*"})`
2. Pass an `OpenStruct` or `Hashie::Mash` instead of a simple hash:  
   `git.describe(nil, OpenStruct.new(match: "*foo*"))`

Great lib, btw.

**Comment by no-trick-pony** [comment] 2017-10-24 13:36
Duplicate of #251

**Closed** 2018-04-09 02:57 UTC
Labels: wontfix
